Repository review-me-blog/review-me-blog.github.io, pull requests merged in 2024-08, with the labels that each got.

#46 docs: 2024-07-30 회의록 작성
  docs/meetingnotes/2024-07-30-meetup/index.md
Labels: 📚 Meetup

#48 docs: 랜덤 블로그 작성
  blog/2024-08-19-random/img/random.webp
  blog/2024-08-19-random/img/rfc.webp
  blog/2024-08-19-random/img/securerandom.webp
  blog/2024-08-19-random/img/threadlocal.webp
  blog/2024-08-19-random/index.mdx
  docusaurus.config.js
Labels: 📕 BE

#51 fix : 블로그에서 리뷰미 시연 영상 오류 수정
  blog/2024-08-26-release-version-1/index.mdx
Labels: 🐛 Bug

#54 docs: 우리 팀에 맞는 도메인 설계는 무엇일까? 글 작성
  blog/2024-08-27-domain-design-2/image/first_erd.png
  blog/2024-08-27-domain-design-2/index.mdx
Labels: 📕 BE
